name: Nightly Build

on:
  push:
    branches:
      - master
    paths:
      - "packages/**"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x86-64
          - os: ubuntu-24.04-arm
            platform: linux
            arch: aarch64
          - os: windows-latest
            platform: windows
            arch: x86-64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Cache LuaJIT
        id: cache-luajit
        uses: actions/cache@v5
        with:
          path: luajit-${{ matrix.platform }}-${{ matrix.arch }}
          key: luajit-${{ matrix.platform }}-${{ matrix.arch }}-latest

      - name: Download LuaJIT
        if: steps.cache-luajit.outputs.cache-hit != 'true'
        run: |
          curl -L -o luajit.tar.gz https://github.com/codebycruz/lj-dist/releases/download/latest/luajit-${{ matrix.platform }}-${{ matrix.arch }}-gnu.tar.gz
          tar -xzf luajit.tar.gz
          chmod +x luajit-${{ matrix.platform }}-${{ matrix.arch }}/luajit${{ matrix.platform == 'windows' && '.exe' || '' }}

      - name: Build lpm (Unix)
        if: matrix.platform != 'windows'
        run: |
          cd packages/lpm
          BOOTSTRAP=1 $GITHUB_WORKSPACE/luajit-${{ matrix.platform }}-${{ matrix.arch }}/luajit ./src/init.lua compile

      - name: Build lpm (Windows)
        if: matrix.platform == 'windows'
        run: |
          cd packages/lpm
          $env:BOOTSTRAP=1; & "$env:GITHUB_WORKSPACE/luajit-windows-x86-64/luajit.exe" ./src/init.lua compile

      - name: Upload artifact (Unix)
        if: matrix.platform != 'windows'
        uses: actions/upload-artifact@v6
        with:
          name: lpm-${{ matrix.platform }}-${{ matrix.arch }}
          path: packages/lpm/lpm
          if-no-files-found: error

      - name: Upload artifact (Windows)
        if: matrix.platform == 'windows'
        uses: actions/upload-artifact@v6
        with:
          name: lpm-${{ matrix.platform }}-${{ matrix.arch }}
          path: ${{ github.workspace }}\packages\lpm\lpm.exe
          if-no-files-found: error
