name: Nightly Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download previous lpm release
        run: |
          gh release download --repo ${{ github.repository }} --pattern "lpm-linux-x86_64"
          chmod +x ./lpm-linux-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bundle new lpm
        working-directory: lpm/packages/lpm
        run: ../../../lpm-linux-x86_64 bundle

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lpm-linux-x86_64
          path: lpm/packages/lpm/lpm
