name: Nightly Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      # - name: Download previous lpm release
      #   run: |
      #     gh release download --repo ${{ github.repository }} --pattern "lpm-linux-x86_64"
      #     chmod +x ./lpm-linux-x86_64
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup luajit
        run: |
          sudo apt-get update
          sudo apt-get install -y libluajit-5.1-dev

      - name: Bundle new lpm
        run: |
          cd packages/lpm
          BOOTSTRAP=1 luajit ./src/init.lua compile

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: lpm-linux-x86_64
          path: ./packages/lpm/lpm

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Download previous lpm release
        shell: bash
        run: |
          gh release download --repo ${{ github.repository }} --pattern "lpm-windows-x86_64.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup luajit
        run: |
          winget install luajit --accept-source-agreements --accept-package-agreements
          choco install pkgconfiglite

      - name: Bundle new lpm
        shell: bash
        run: |
          cd packages/lpm
          $GITHUB_WORKSPACE/lpm-windows-x86_64.exe install
          $GITHUB_WORKSPACE/lpm-windows-x86_64.exe compile --outfile ./lpm-windows-x86_64.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: lpm-windows-x86_64
          path: packages/lpm/lpm-windows-x86_64.exe
