name: Nightly Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Download previous lpm release
        run: |
          gh release download --repo ${{ github.repository }} --pattern "lpm-linux-x86_64"
          chmod +x ./lpm-linux-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup luajit
        uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: "luajit-2.1.0-beta3"

      - name: Bundle new lpm
        run: |
          cd packages/lpm
          $GITHUB_WORKSPACE/lpm-linux-x86_64 bundle ./newlpm

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: lpm-linux-x86_64
          path: packages/lpm/newlpm
