name: Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Download previous lpm release
        run: |
          gh release download --repo ${{ github.repository }} --pattern "lpm-linux-x86_64"
          chmod +x ./lpm-linux-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup luajit
        run: |
          sudo apt-get update
          sudo apt-get install -y libluajit-5.1-dev

      - name: Bundle new lpm
        run: |
          cd packages/lpm
          $GITHUB_WORKSPACE/lpm-linux-x86_64 install
          $GITHUB_WORKSPACE/lpm-linux-x86_64 bundle ./lpm-linux-x86_64

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: packages/lpm/lpm-linux-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
